### ISSUE TITLE
Add option to open chrome in incognito mode

### ISSUE THREAD

**Issue by flesnuk** [jack-mil/bing-rewards#10]
Just to avoid polluting the history with all the searches made.

Thank you for this little tool, very useful and easy to use.

Edit: I just realized that by doing this, you are not logged in lol. Nvm then

**Comment by jack-mil** [comment]
Hi @flesnuk , this would be a nice feature. The thought had occurred to me, but I came to the same conclusion you did. Operating in incognito mode would require signing into bing every run, which didn't seem ideal. 
Glad you get some use out of this :D

**Comment by flesnuk** [comment]
Yeah, at least I see there is no problem in setting the exe for the Edge browser (which I don't use) so for me that already solves it 😃 

Also, it's a shame in Europe the rewards are lower than US. (150pts vs 90pts for PC and 100pts vs 60pts for mobile). But still it is 6~7€ monthly for free.
