### ISSUE TITLE
Mobile not working

### ISSUE THREAD

**Issue by JonrGull** [jack-mil/bing-rewards#13]
It's possible this is entirely due to user error, but when I run the command to spoof mobile, it doesn't count the searches. Desktop seems to work fine.

Is it something I'm doing wrong? Or did Microsoft change something?

**Comment by jack-mil** [comment]
I'm going to look into this. I have noticed a similar issue occasionally when I use it with Edge. I think there might have been some breaking change related to the user agent.

**Comment by JonrGull** [comment]
I'm not great at Python, but I will take a look around as well. I do believe they changed something within the past two weeks or so. Sorry that isn't very helpful.

Unsure if you have upgraded to Windows 11 yet, but I just wanted to let you know that it still works, albeit I can't quite figure out the PATH part.

So I just do a direct path to my Edge browser and it works wonderfully outside of the mobile points.

**Comment by jack-mil** [comment]
Interesting, so I tried using Brave instead of Edge (Both chromium browsers with the --user-agent switch) and it seems to load the mobile versions of Bing's website. I think this might be a change in the Edge Browser that doesn't load the user agent from the command line switch. 
It is working with the latest version of Brave, 1.43.93 (Chromium 105.0.5195.127)

**Comment by JonrGull** [comment]
I see! Yes when I ran this command on Brave the switch works and it counts mobile searches. So you're right, it's possible it's a browser issue. 

It seems Brave is the only one that works for now then.

**Comment by JonrGull** [comment]
I tried changing the user agent string in the config file in APPDATA, using the device emulation tool, and[ this site to generate the string.](https://www.whatismybrowser.com/detect/what-is-my-user-agent/)

I kind of have a feeling that my settings are not being taken into account, but it's possible the fix would be more complicated than that.

**Comment by spupuz** [comment]
does this also does the quizzes?

**Comment by jack-mil** [comment]
Unfortunately, no, that is beyond the scope I was going for. There are some much for complex tools with more dependencies which might, if they still work

**Comment by rahul-s-bhatt** [comment]
@jack-mil @JonrGull I m not able get mobile points with brave/edge, is there a fix for this in 2023?

**Comment by jack-mil** [comment]
> @jack-mil I m not able get mobile points with brave/edge, is there a fix for this in 2023?

One thing I have noticed is that all browser processes have to be shut down when launching with the --user-agent flag in order for it to take effect. Example, I can't have a Brave PWA open in another window while loading a instance with mobile user agents. I assume Edge (Chromium) acts similarly. 

I can do some testing with Edge specifically. sometimes it is hit or miss

**Comment by N190392** [comment]
For me it still does not work on either Chrome or Brave (Edge seems to ignore completely mobile user agent). Tried to change user agents, still no luck
I even ran:
```
taskkill /f /im "chrome.exe"
taskkill /f /im "brave.exe"
```
before the script. Browser opens, does searches in mobile view, but I still see 0/60 mobile searches.
Maybe agents need to be updated? This is my config:
```
{
    "desktop-count": 34,
    "mobile-count": 40,
    "load-delay": 1.5,
    "search-delay": 2,
    "search-url": "https://www.bing.com/search?q=",
    "desktop-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 Edg/83.0.478.37",
    "mobile-agent": "Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Mobile Safari/537.36 Edge/18.19041",
    "browser-path": "C:\\Users\\G\\AppData\\Local\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"
}
```

**Comment by jack-mil** [comment]
@N190392 
Can you try this user agent string for mobile in your config?
I did some testing with Chrome `112.0.5615.138` and noticed the issue you are having.
Changing the user agent to list a newer browser version worked for me
`Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1`

**Comment by N190392** [comment]
Unfortunately still no luck..

**Comment by tobfromme** [comment]
My mobile is working with Chrome 112.0.5615.165 on Linux.  My config.json:
`{
    "desktop-count": 100,
    "mobile-count": 100,
    "load-delay": 1.5,
    "search-delay": 2,
    "search-url": "https://www.bing.com/search?q=",
    "desktop-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 Edg/83.0.478.37",
    "mobile-agent": "Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Mobile Safari/537.36 Edge/18.19041",
    "browser-path": "/usr/bin/google-chrome-stable"
}
`
