### ISSUE TITLE
Unexpected error: [Errno 2] No such file or directory: 'chrome'

### ISSUE THREAD

**Issue by 3kh0** [jack-mil/bing-rewards#15]
I have installed chrome, you can run it using `google-chrome`. Yet I still get the error.

![image](https://user-images.githubusercontent.com/58097612/217330232-8e7b4936-f531-486f-9157-5723c067564a.png)

running with root
![image](https://user-images.githubusercontent.com/58097612/217330678-aca8e8b5-5fad-4f16-b730-596ceca28d8f.png)

running without root
![image](https://user-images.githubusercontent.com/58097612/217330798-ec364a14-4067-43c3-be3a-a5a479701b4a.png)

**Comment by jack-mil** [comment]
The script tries to find the command `chrome` on path (from the windows chrome.exe).
 If your executable is called `google-chrome`, then you will want to modify the --exe flag or use the config file to set the browser executable.
Hope this helps :)

**Comment by 3kh0** [comment]
Ok, thanks, the mobile method does not work

**Comment by jack-mil** [comment]
Yes, this hasn't been tested in a while and I believe some changes to the user agent flag may have broken the mobile method. See Issue #13. If I get a chance , I'll look into it. I haven't personally used this in a while, so recent updates may have broken things

**Comment by 3kh0** [comment]
Alright thanks!
