### ISSUE TITLE
Script is just an auto-typer

### ISSUE THREAD

**Issue by Chaython** [jack-mil/bing-rewards#33]
Basically all of it is redundant, as it seems to just type into the text field in any chrome browser
[I set brave it opens bracee] I click away, it starts typing in edge...
Mobile agent doesn't work for me in any browser

**Comment by jack-mil** [comment]
Yes, just being an auto typer is the scope of this project. There are several other tools floating around on GH that are fully automated and headless. They use headless Chrome Drivers and Selenium. My goal for this script was to be as simple as possible and require minimal dependencies. 

As for the mobile agent issue, that seems to be very hit or miss. Several other have reported intermittent and random (?) success. Most of the time it has worked for me. I think most of it is beyond my control by just setting a simple user agent. It is possible that Bing and/or Chromium is constantly changing it's detection of a mobile device
