### ISSUE TITLE
My Account got suspended using this, any ways to avoid this or get back this account?

### ISSUE THREAD

**Issue by rahul-s-bhatt** [jack-mil/bing-rewards#34]

**Comment by rahul-s-bhatt** [comment]
@jack-mil Hi, sorry for the late reply.
I have been using it since I found it out, I guess 4-5 Months.
This month I think I would have redeemed two gift cards (back to back within 24 hours I guess).
I have also checked out r/bing rewards (don't remember the name) and seen people get banned for no reason, I think it is the AI that banned the ppl for the wrong/no reason.

Anyways, did anyone else get flagged?

**Comment by riahc3** [comment]
@rahul-s-bhatt You probably ran the program several times a day and/or made a batch program that runs it every day and the same time.
