### ISSUE TITLE
search-url config parameter ignored

### ISSUE THREAD

**Issue by Netti93** [jack-mil/bing-rewards#38]
The script does not use the config value for search-url but just the hardcoded default URL value.

**Comment by tobfromme** [comment]
Agreed.  I'm finding the rewards aren't occurring today, so I was playing with this parameter only to find the same thing.

**Comment by jack-mil** [comment]
oop, you are totally right. I added that to the config file, but never used it, so forgot to implement that feature in the code. 
I'll work on it soon™️ .
Has bing changed recently that the old link is no longer working? I haven't used this personally in a while, so I don't know the current status

**Comment by Netti93** [comment]
It seems like they require some query parameter that are only added when searched via search field because a search directly within the address bar without any (additional) params is not working while the same search within the search field does give you the points.

**Comment by tobfromme** [comment]
For me, I noticed the points haven't been appearing the past few days, and that Chrome, Chromium, and Edge all hang on Bing when using bing-rewards.  When running any of these browsers manually, by hitting ESC after bing-rewards starts, I can get the points to work.  I figured I would play with the URL to see if that's it, and that's when I discovered the config option wasn't used.

I'm not sure what's up with the bing points issue though.  Seems like they are getting more intelligent at watching.  Maybe a random timer would help (i.e. in the config set a min and max timer and then find a random point in between those).

**Comment by tobfromme** [comment]
@Netti93 are you on Linux or Windows?  My points issue is occurring on Linux, which prompted me to try the search-url configuration parameter.

**Comment by Netti93** [comment]
I'm on Windows and for me it started today.

**Comment by crazydave48** [comment]
Just confirming that I'm having the same issue. The script still runs fine, just got getting any points for each search. I haven't noticed till today but I'm sure it's been happening for a bit now.

**Comment by jungx098** [comment]
It looks like Bing now requires search queries to include FORM. If you don't get any points, try https://github.com/jack-mil/bing-rewards/pull/39.

**Comment by crazydave48** [comment]
That worked! Thanks everyone who helped get this fixed!
