### ISSUE TITLE
Mobile Drivers not running

### ISSUE THREAD

**Issue by vinayaka16041999** [jack-mil/bing-rewards#44]
The program is not able to claim mobile rewards as the script is not opening the mobile bing sites. Even after the script runs no mobile points are added.

**Comment by jack-mil** [comment]
It is very likely that enough has changed both with the bing.com website and how it detects/handles user agent and mobile detection. It is even possible that Bing does not offer bonus points for mobile searches anymore. This entire project was made and worked well before the "AI Era" of Bing/Copilot, so a lot is different now.

**Comment by Wakeelfahmed** [comment]
Yes the searches for mobile not awarded, but the issue is at Microsoft's end.

I did from Phone (Edge Browser), and didnt got rewarded. but then I did with Bing App (not edge, its a seperate app), the rewards are credited. 

https://play.google.com/store/apps/details?id=com.microsoft.bing&pli=1

**Comment by rajdedhia10** [comment]
Update the user strings. I've tested them and they work perfectly for both mobile and desktop.

Mobile -
`Mozilla/5.0 (Linux; Android 14; Pixel 6 Build/AP2A.240605.024; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36 EdgA/121.0.2277.138`

Desktop -
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`

**Comment by supertriodo** [comment]
Updated to 3.0 but mobile searches still don't work.

**Comment by jack-mil** [comment]
@supertriodo 
> Updated to 3.0 but mobile searches still don't work.

Right, does Microsoft even offer bonus points for a mobile browser anymore? My page doesn't even show that as an options anymore. It just says "PC Search". 
Honestly, I think this tool is going to be very hit and miss now. It was originially made years ago before Bing got all AI enhanced and was much simpler to use. 
I think there are other search detection measures in place now besides just a simple browser user agent string.
Try a combination of the different options; browsers (chrome, brave, edge itself), using the `--bing` flag and setting bing as the default search engine for a certain profile (`--profile`), or adjusting the delay timings. If something works for you, please let us know!
