### ISSUE TITLE
Request to add the search queries

### ISSUE THREAD

**Issue by charbeljacob** [jack-mil/bing-rewards#47]
Most of my accounts got banned today lol. i cultivated that for months. i don't know how i got caught. Anyway, as the title suggest, it is nice to have updated search queries.

**Comment by jack-mil** [comment]
What exactly are you referring to? Do you mean some new url query strings that Bing has rolled out? I haven't personally used this project in probably 2 years, so I'm actually surprised it is even working anymore with how much Bing has changed in the AI age.

**Comment by charbeljacob** [comment]
> What exactly are you referring to? Do you mean some new url query strings that Bing has rolled out? I haven't personally used this project in probably 2 years, so I'm actually surprised it is even working anymore with how much Bing has changed in the AI age.

yes haha. i have been using this for at least 3 months and it worked pretty well. desktop searches are ok but mobile searches dont. i have been redeeming small value gift cards and i have been successful but they get banned sometimes. but just today all my accounts got banned. so yeah ty for the project
