### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by Tri4ceKid** [jack-mil/bing-rewards#56]
I'm just trying to get to the config file to edit arguments, but it's not there... nothing is.
![Screenshot 2024-11-28 095825](https://github.com/user-attachments/assets/7aefe8dd-a142-4adb-8b16-81b5de4ec023)

Apologies in advance, am big noob

**Comment by Tri4ceKid** [comment]
Took a bit of digging, but I found the config file in ~\AppData\Local\Packages\PythonSoftware...\LocalCache\Roaming\bing-rewards. Not sure why it saved there, but that appears to have solved my issue.

**Comment by jack-mil** [comment]
That is really strange... Do you have Python installed through the Microsoft Store? 
Even still, I am surprised it messed up the paths. [These are the paths that are supposed to be searched](https://github.com/jack-mil/bing-rewards/blob/af7137347d7a2ed4c127f7e54a6dcf0a8ec8769e/bing_rewards/options.py#L161C1-L176C47).
I am guessing that the MS Store distribution of Python overrides the $APPDATA environment variable.
```py
def config_location() -> Path:
    r"""Check these locations in order for config.json.


    - %APPDATA%\bing-rewards\
    - $XDG_CONFIG_HOME/bing-rewards/
    - $HOME/.config/bing-rewards/
    """
    # Config file in .config or APPDATA on Windows
    config_home = Path(
        os.environ.get('APPDATA')
        or os.environ.get('XDG_CONFIG_HOME')
        or Path(os.environ['HOME'], '.config'),
        'bing-rewards',
    )


    return config_home.joinpath('config.json')
    ```

**Comment by Tri4ceKid** [comment]
It was a long time ago that so I'm not 100% certain, but I'm pretty sure it was installed through the Microsoft Store.
