### ISSUE TITLE
config file?

### ISSUE THREAD

**Issue by EQNish** [jack-mil/bing-rewards#6]
with the newest version, is there no longer a Bing_search.py config file?
In an older version I was able to set the LOAD_DELAY and SEARCH_DELAY as well as hard set the browser "--exe" to my chromium of choice!

**Comment by jack-mil** [comment]
If I had that before, I don't remember haha.
But it is a good idea, and I will look into implementing it. Now that the tool is a pypi package, configuration file will probably have to be set in the user ~ directory. 
For reference, the --exe flag and other options could be set in a shell alias or windows shortcut target. But some user may prefer a static config file, which shouldn't be too hard to implement.

**Comment by jack-mil** [comment]
This feature will be implemented in the next release (1.3.0)

**Comment by EQNish** [comment]
thanks, the delay was exactly what I needed! plus the added bonus for --exe!!!
